import PDFDocument from "pdfkit";

export type FarmReportData = Awaited<ReturnType<typeof import("./db").getFarmDetails>>;

export async function buildFarmReportPdf(data: FarmReportData) {
  const doc = new PDFDocument({ size: "A4", margin: 48, info: { Title: `${data.farm.name} Farm Report`, Author: "Mavuno Potato Care" } });
  const chunks: Buffer[] = [];
  const finished = new Promise<Buffer>((resolve, reject) => {
    doc.on("data", (chunk: Buffer) => chunks.push(chunk));
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);
  });
  doc.fillColor("#153d2c").fontSize(24).text("Mavuno Potato Care");
  doc.fillColor("#355141").fontSize(17).moveDown(0.4).text(`${data.farm.name} · Farm report`);
  doc.fillColor("#718178").fontSize(10).text(`${data.farm.location ?? "Location not set"} · ${data.farm.acreage ?? "Acreage not set"}`);
  doc.moveDown(1).strokeColor("#dfe8d9").lineWidth(1).moveTo(48, doc.y).lineTo(547, doc.y).stroke();
  doc.moveDown(1).fillColor("#153d2c").fontSize(13).text("Summary");
  doc.fillColor("#52665a").fontSize(10).moveDown(0.4).text(`Fields: ${data.fields.length}    Open tasks: ${data.tasks.filter((task) => !task.completed).length}    Diagnosis records: ${data.diagnoses.length}`);
  doc.moveDown(1).fillColor("#153d2c").fontSize(13).text("Fields and varieties");
  for (const field of data.fields) {
    doc.fillColor("#355141").fontSize(11).moveDown(0.4).text(`${field.name} · ${field.variety ?? "Variety not set"}`);
    doc.fillColor("#718178").fontSize(9).text(`Acreage: ${field.acreage ?? "not set"} · Planted: ${field.plantedAt ? new Date(field.plantedAt).toLocaleDateString() : "not set"} · Health: ${field.healthScore}/100`);
  }
  doc.moveDown(1).fillColor("#153d2c").fontSize(13).text("Farm activity");
  for (const task of data.tasks.slice(0, 20)) {
    doc.fillColor("#52665a").fontSize(9).text(`${task.completed ? "[x]" : "[ ]"} ${task.title}${task.description ? ` — ${task.description}` : ""}`);
  }
  doc.moveDown(1).fillColor("#153d2c").fontSize(13).text("Diagnosis history");
  for (const diagnosis of data.diagnoses.slice(0, 30)) {
    doc.fillColor("#52665a").fontSize(9).text(`${new Date(diagnosis.createdAt).toLocaleDateString()} · ${diagnosis.diseaseName} · ${diagnosis.confidence}% confidence`);
    if (diagnosis.symptoms) doc.fillColor("#718178").text(`Symptoms: ${diagnosis.symptoms}`);
  }
  doc.moveDown(1).fillColor("#8a998e").fontSize(8).text("Generated by Mavuno Potato Care. AI crop diagnoses are advisory and should be confirmed by a qualified agronomist when uncertain.");
  doc.end();
  return finished;
}
